### PR TITLE
styles/ central background gradient

### PR DESCRIPTION
**Pull request by shpomp**
# Description
TEMPORARILY centralizing background gradient to the App. 
Each team can adjust accordingly. 

# Jira task link
Admin has no jira board 😭

### CODE REVIEW

**Comment by danJecu** [comment]
On the landing page we have the gradient with multiple directions. 
I think the first section has the gradient from left with black, next section has the black from right but a different percentage and the last section has the black from the bottom 😄.

I see that View has the exact same pattern as us but List had a different one. 

Should we just overwrite? 👨‍🎤

image

**Comment by shpomp** [comment]
> On the landing page we have the gradient with multiple directions. I think the first section has the gradient from left with black, next section has the black from right but a different percentage and the last section has the black from the bottom 😄.
> 
> I see that View has the exact same pattern as us but List has a different one.
> 
> Should we just overwrite? 👨‍🎤
> 
> image

Oh, I did not notice and did not consider 🤦🏽 
The approaches you all take for the page containers are also a bit different.... 😅 
Let me try to come up with a solution 💡

**Comment by shpomp** [comment]
@danJecu  I thought it is the same gradient that just stretches differently in different size.... is it not? 
I am looking at it again and looks the same to me :D

**Comment by danJecu** [comment]
Screen Shot 2023-05-14 at 18 45 39

**Comment by shpomp** [comment]
> This is how I see it, and I think is very doable by setting the gradient on different angles on each section of the page. Screen Shot 2023-05-14 at 18 45 39

Let's push this so we have some central gradient for the time being (rather than having it coming from a MovieDetails container only), and each team can fix it accordingly?

**Comment by danJecu** [comment]
That's perfect!

**Pull request merged**
