### PR TITLE
fix/ update missing movie posters

### PR DESCRIPTION
**Pull request by shpomp**
# Description
Fixed all the 404 movie posters. 

https://github.com/HackYourFuture-CPH/CINEMANIA/assets/64137994/84eca682-4309-45a4-974f-bed3ddca7021

```
const URL = (query) =>
  `https://api.themoviedb.org/3/search/movie?api_key=${APIkey}&language=en-US&query=${query}&page=1&include_adult=false`;

const getMovies = () => {
  fetch("http://localhost:5001/api/movies", {
    method: "GET",
    headers: {
      Accept: "application/json",
    },
  })
    .then((response) => {
      return response.json();
    })
    .then((data) => {
      data.map(async (movie) => {
        const imageResponse = await fetch(movie.image_location);
        if (imageResponse.status === 404) {
          await fetchImageURL(movie);
        }
      });
    })
    .catch((err) => console.error(err));
};

async function fetchImageURL(movie) {
  const { title } = movie;
  const query = encodeURIComponent(title);

  const searchResponse = await fetch(URL(query));
  const searchData = await searchResponse.json();
  const newImageURL = searchData.results[0]?.poster_path;

  return {
    ...movie,
    image_location: "https://www.themoviedb.org/t/p/w1280/" + newImageURL,
  };
}
```

### CODE REVIEW

**Comment by danJecu** [comment]
Can you also get some of the ones in landscape format? We need them for featured section 😃

**Review by danJecu — APPROVED** [review]
Cool 🥇

**Comment by shpomp** [comment]
> Can you also get some of the ones in landscape format? We need them for featured section 😃

Talking to Vipee today in standup, I realized we did not think it through. We would need another column for the different image location for each movie? 
I say let's plan that the feature movie is always hard-coded, a great weekly task for the junior developer in the CINEMANIA startup :D

**Comment by shpomp** [comment]
> > Can you also get some of the ones in landscape format? We need them for featured section 😃
> 
> Talking to Vipee today in standup, I realized we did not think it through. We would need another column for the different image location for each movie? I say let's plan that the feature movie is always hard-coded, a great weekly task for the junior developer in the CINEMANIA startup :D

https://github.com/HackYourFuture-CPH/CINEMANIA/pull/95/files

**Pull request merged**
