### PR TITLE
Created Edit Rating Button, to navigate unauthenticated user to signup…

### PR DESCRIPTION
**Pull request by Aditi-Sawardekar**
… page.

# Description: Create "edit review button", if the user is not authenticated, send to log in page.

# Jira task link: https://hackyourfuture-dk.atlassian.net/browse/VIEW-68

# Screenshots (if applicable)
Edit Button

Navigates to Login Page

### CODE REVIEW

**Review by shpomp — CHANGES_REQUESTED** [review]
This is a good implementation in itself, however, not a great UX. 
If the user is not logged in, they should not see a button to edit the rating. It would be better if a non-authenticated user gets an option to rate, and then gets redirected to the login (or informed in a modal and given the option to go to the login) 🙏🏽 
So a state where user is not logged in or has not rated the move looks the same in UI, just gives different outcomes when clicking the element to rate the movie.

**Comment by Aditi-Sawardekar** [comment]
Hi,
Will try to make the necessary changes.
What I understand here is:
If the user in not logged in, he will see the same UI (Rating options)
When he clicks on the rating, he will be navigated to the login page.

**Comment by shpomp** [comment]
> Hi, Will try to make the necessary changes. What I understand here is: If the user in not logged in, he will see the same UI (Rating options) When he clicks on the rating, he will be navigated to the login page.

@Aditi-Sawardekar let me know if this helps! 

image

**Comment by Aditi-Sawardekar** [comment]
Hi Karo,
I have reworked and submitted the code
- In the beginning it shows rating stars.
- When the user tries to edit rating
     - If the user is authenticated he can see the edit rating option
     - If the user is unauthenticated, he gets message You are not logged in , with link to LogIn Page.
     
The second part,
Will work on the second part in another PR....

**Review by shpomp — APPROVED** [review]

**Comment by Aditi-Sawardekar** [comment]
Thank you

**Pull request merged**
