### PR TITLE
Fixed issues with get movies list endpoints.

### PR DESCRIPTION
**Pull request by shobanamg**
# Description
Fixed SQL error with knex query.

Moved movie list endpoint to a separate router, since it was not reaching the /movies/list with the existing implementation. 
I need an endpoint for the team to work, I will investigate later, why the movies/list route is not working, it was always returning 200 with an empty body

Updated the query to return if it is the favorite for the given userId

# Jira task link
https://hackyourfuture-dk.atlassian.net/browse/LIST-8

# Screenshots (if applicable)

### CODE REVIEW

**Comment by itsgauravsaxena** [comment]
I am not sure if I follow this quite. So endpoint doesnt work but you want to merge it?

**Comment by shobanamg** [comment]
It was not working with the movies route, so I have created a separate movie list route. That is working.

**Comment by itsgauravsaxena** [comment]
@shobanamg Could you please add screenshot or test endpoints that I can refer

**Comment by shobanamg** [comment]
> @shobanamg Could you please add screenshot or test endpoints that I can refer

@itsgauravsaxena, Please find the screenshot of the postman. 
New Note

**Review by itsgauravsaxena — APPROVED** [review]

**Pull request merged**
